hils_servo_pwm_bridge:
  ros__parameters:
    serial_port: /dev/ttyACM0
    baudrate: 115200
    joint_state_topic: /servo_pwm/joint_states
    pulse_topic: /servo_pwm/pulses_us
    servo_channels: 4
    servo_min_angle: -1.5708    # -pi/2
    servo_max_angle: 1.5708     # pi/2
    servo_min_pulse_us: 500
    servo_max_pulse_us: 2500
    joint_names: ['']           # Empty = "servo_<channel>"
